# encoding: utf-8

require 'rubygems'
require 'bundler'

DIR_ROOT = File.expand_path(File.dirname(__FILE__))
$LOAD_PATH.unshift File.join(DIR_ROOT, 'lib')
Dir.glob('lib/**').each{ |d| $LOAD_PATH.unshift(File.join(DIR_ROOT, d)) }

begin
  Bundler.setup(:default, :development)
rescue Bundler::BundlerError => e
  $stderr.puts e.message
  $stderr.puts "Run `bundle install` to install missing gems"
  exit e.status_code
end

require 'rake'
require 'irb'

desc 'Start the console'
task :console do
  ARGV.clear
  IRB.start
end
